language: cpp
matrix:
  include:
    - os: linux
      dist: bionic
    - os: osx
      osx_image: xcode11
    - os: osx
      osx_image: xcode12
addons:
  apt:
    packages:
      - scons
  homebrew:
    packages:
      - scons
git:
  submodules: true
script:
  - scons -j2 test
  - scons -j2
  - python3 -m unittest discover .
deploy:
  provider: pypi
  username: "__token__"
  password:
    secure: EPAz6V3vWB5MWIJejLtofZKAL6Kvy9tKUZlZlbtiaQr8lMF/Cr4pfG5u1oczQpYGNZEKwXY70Gy1Eo9eff1mHaXWcnpU3HzxWoDyvIpUwBnaaqvfdusHowQ56I7/KRLwqSzN6oi3Srdd5DEb4IQSRIeUbmm2V/hEbFI+FNCXj8/uY4JSKTPoUyokpj9jAE7FEkfkJLlQIT8aSnExYCF9poeEItqGuNmMRe4kxGGhjw1FHAdJYQIeAzldu356nk0E5dDMFtzFyUqBUdhyRbNXzNkdgymTc1zc4anOQBi7HyYrZZQl+Kbgl8OQBCtROO0MVnUYMo4+tslCjWiih4w3DX27ex3YcgulyNmbrd0UOV+5eJLeWkgeO7Sr+NpZ8Jbq9zGm1pUR3TEuYAnNLacw1gJAKBvo/htIiT885kZ3Mzx27XgYPzb6Zqig4sT/ZMBGf8LBBDNrPlq90IByj9x3BgEUN2E1YK623JwyqVXVvwyiyDp8mVeY2sNJFiKisfKFNF/RMsE5pRDikEWITi4+61BLp3qyIUVo1Ez0azlInoHr1G5o4uZ3gMlQ7n0/90PuO76xf07scGUThYqxaL5FyACKHyoNhFK16C08lYSlxpp7boNSiQHNE4ETBC9BfRI5nY0oS8ylTKNKcUQyom4xZyrL6zBq6UStLoMUmDOnVjs=
  on:
    tags: true
  distributions: "sdist bdist_wheel"
  skip_existing: true
