language: cpp
matrix:
  include:
    - os: linux
      dist: bionic
    - os: osx
      osx_image: xcode11
    - os: osx
      osx_image: xcode12
addons:
  apt:
    packages:
      - scons
  homebrew:
    packages:
      - scons
git:
  submodules: true
script:
  - scons -j2 test
  - scons -j2
  - python3 -m unittest discover .
